services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: recepcao62bi
      POSTGRES_USER: recepcao62bi
      POSTGRES_PASSWORD: recepcao62bi

  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "project.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://recepcao62bi:recepcao62bi@db:5432/recepcao62bi

volumes:
  postgres_data:
