# Generated by Django 4.2.13 on 2024-06-17 23:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento')),
                ('secao', models.CharField(choices=[('Fusex', 'Fusex'), ('Medico', 'Medico'), ('Dentista', 'Dentista'), ('SVP', 'SVP'), ('Secretaria', 'Secretaria'), ('Protocolo', 'Protocolo'), ('SecMob', 'SecMob'), ('SFPC', 'SFPC'), ('Enfermaria', 'Enfermaria'), ('Relações Publicas', 'Relações Publicas')], max_length=50, verbose_name='Seção')),
                ('data', models.DateTimeField(default=app.models.default_date)),
            ],
        ),
    ]
